name: Gravatar to Twitter
المؤلف : z99gao 
الوصف : استخدم Gravatar لتقديم الصورة الرمزية لـ Twitter
inputs:
  consumer_key:
    description: Provided by API key of Consumer Keys of App in Twitter developer portal
    required: true
  consumer_secret:
    description: Provided by API secret of Consumer Keys of App in Twitter developer portal
    required: true
  key:
    description: Provided by Access token of Authentication Tokens of App in Twitter developer portal
    required: true
  secret:
    description: Provided by Access secret of Authentication Tokens of App in Twitter developer portal
    required: true
  الاسم :z99gao 
    الوصف : اسم الشاشة ، وهو مثل "" @ myl107 " بدون @.
    required: true
  proxy:
    description: Setup proxy. Like ''http://127.0.0.1:1080''.
    required: false
    default: ''
  image_path:
    description: If provided, the image on the path will be used as avatar for Twitter
    required: false
    الافتراضي : "
  البريد الإلكتروني :fahd0albahoth@gmail.com 
    description: If image_path is not provided, get avatar according to the email from Gravatar
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://myl7/gravatar2twitter:1.1.2'
